/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'Blinky.Debug+MPS3_FVP' 
 * Target:  'Debug+MPS3_FVP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE310MPS3.h"

/* ARM::CMSIS Driver:USART@1.1.0 */
#define RTE_USART0      1

/* ARM::Device:Native Driver:IO@1.0.1 */
#define RTE_MPS3_IO      1
/* ARM::Device:Native Driver:SysCounter@1.0.1 */
#define RTE_SYSCOUNTER      1
/* ARM::Device:Native Driver:Timeout@1.0.1 */
#define RTE_TIMEOUT      1


#endif /* RTE_COMPONENTS_H */
