/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'Blinky' 
 * Target:  'Simulator' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE310MPS3.h"

/* ARM::CMSIS-Compiler:STDOUT:Event Recorder@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Event_Recorder /* CMSIS-Compiler STDOUT: Event Recorder */
/* ARM::CMSIS-View:Event Recorder&DAP@1.6.0 */
#define RTE_CMSIS_View_EventRecorder
#define RTE_CMSIS_View_EventRecorder_DAP
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
#define RTE_CMSIS_RTOS2_RTX5_ARMV8M_NS  /* CMSIS-RTOS2 Keil RTX5 Armv8-M Non-secure domain */


#endif /* RTE_COMPONENTS_H */
